global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'core-booking-1'
    scrape_interval: 1s
    metrics_path: '/actuator/prometheus'
    static_configs:
     - targets: ['core-booking-1:8080']
  
  - job_name: 'core-booking-2'
    scrape_interval: 1s
    metrics_path: '/actuator/prometheus'
    static_configs:
     - targets: ['core-booking-2:8080']
  