server:
  port: 8080

#external:
#  core-booking:
#    url: ${CORE_BOOKING_URL}
#  core-catalog:
#    url: ${CORE_CATALOG_URL}
#  core-catalog-writer:
#    url: ${CORE_CATALOG_WRITER_URL}
#  core-registry:
#    url: ${CORE_REGISTRY_URL}

spring:
  security:
    authorities:
      CLIENT:
        - CLIENT
      LIBRARY:
        - LIBRARY
      MODERATOR:
        - CLIENT
        - MODERATOR
  datasource:
    url: jdbc:postgresql://localhost:5432/gateway-master #${SPRING_DATASOURCE_URL}
    username: gateway-owner #${SPRING_DATASOURCE_USERNAME}
    password: gateway-owner #${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver


rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem

logging:
  level:
    org:
      springframework:
        web: DEBUG