server:
  port: 8080

#external:
#  core-booking:
#    url: ${CORE_BOOKING_URL}
#  core-catalog:
#    url: ${CORE_CATALOG_URL}
#  core-catalog-writer:
#    url: ${CORE_CATALOG_WRITER_URL}
#  core-registry:
#    url: ${CORE_REGISTRY_URL}

spring:
  security:
    authorities:
      CLIENT:
        - CLIENT
      LIBRARY:
        - LIBRARY
      MODERATOR:
        - CLIENT
        - MODERATOR
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
  clients:
    core-booking:

      host:

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem

logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG
        web: DEBUG