spring:
  application:
    name: core-booking
  datasource:
    driver: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  kafka:
    consumer:
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: core-catalog-reservations-1
      topic:
        name: core-catalog-reservations
  task-scheduler:
    pool-size: 5
  timeout:
    core-catalog-callback-timeout-millis: 60000
  retry:
    max-attempts: 3
    delay-between-retries-millis: 5000
