server:
  port: 8081

spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS} #localhost:9092
    producer:
      topic:
        name: core-catalog-reservations
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem

logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG
        web: DEBUG